language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - DEFAULT=1
    - COVERAGE=0
    - PHPCS=0

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: PHPCS=1

    - php: 7.3
      env: COVERAGE=1

before_script:
  - phpenv rehash

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

script:
  - if [[ $DEFAULT == 1 ]]; then phpunit; fi

  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

  - if [[ $COVERAGE == 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml || true; fi
  - if [[ $COVERAGE == 1 ]]; then wget -O codecov.sh https://codecov.io/bash; fi
  - if [[ $COVERAGE == 1 ]]; then bash codecov.sh; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
